# Configuración de GitHub Pages
title: "CMS Botones de Venta"
description: "Panel CMS para crear y personalizar botones de venta de eventos - Vista previa en tiempo real"

# Configuración del tema
theme: jekyll-theme-minimal

# Configuración de plugins
plugins:
  - jekyll-github-metadata

# Configuración de archivos a incluir
include:
  - docs/

# Configuración de archivos a excluir
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Configuración de la URL base
baseurl: "/cms-botones-eventos"
url: "https://viernesenvenus.github.io"

# Configuración del directorio de origen
source: docs
